# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    
    - name: Build with Maven
      run: mvn -B package --file tema1/spring-test-ejem2/pom.xml
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.2
      with:
        # GITHUB_TOKEN
        github_token: ${{secrets.GITHUB_TOKEN}}
    - run: mkdir staging && cp tema1/spring-test-ejem2/target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: spring-test-ejem2
        path: staging
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn install -B -DskipTests --file tema1/spring-test-ejem2/pom.xml
        mvn deploy -B -DskipTests --file tema1/spring-test-ejem2/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is the default env for the password

